import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./login.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id" className="">
        <body className="bg-slate-100 dark:bg-slate-900 min-h-screen transition-colors duration-300">
            {children}
        </body>
    </html>
  );
}
